# Generated by Django 5.2.17 on 2026-09-20 11:15

import accounts.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_no', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='사번은 영문 대문자와 숫자 2~20자여야 합니다.', regex='^[A-Z0-9]{2,20}$')], verbose_name='사번')),
                ('full_name', models.CharField(max_length=50, verbose_name='성명')),
                ('role', models.CharField(choices=[('USER', '일반 사용자'), ('ADMIN', '관리자')], default='USER', max_length=10, verbose_name='역할')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='부서')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='비밀번호 변경 필요')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['employee_no'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_employee_no', models.CharField(max_length=20, verbose_name='입력 사번')),
                ('full_name_input', models.CharField(blank=True, max_length=50, verbose_name='입력 성명')),
                ('success', models.BooleanField(default=False, verbose_name='성공 여부')),
                ('fail_reason', models.CharField(blank=True, max_length=30, verbose_name='실패 사유')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '로그인 이력',
                'verbose_name_plural': '로그인 이력',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attempted_employee_no', '-created_at'], name='accounts_lo_attempt_48565d_idx'), models.Index(fields=['-created_at'], name='accounts_lo_created_f638c4_idx')],
            },
        ),
    ]
