# Generated by Django 5.2.17 on 2026-09-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0003_comparisonreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', '엑셀')], max_length=10, verbose_name='형식')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='파일 경로')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='파일명')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='파일 크기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 일시')),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analysis.analysisrun')),
                ('comparison_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analysis.comparisonreport')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리포트 생성 이력',
                'verbose_name_plural': '리포트 생성 이력',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reports_rep_created_ec04fe_idx')],
            },
        ),
    ]
