# Generated by Django 5.2.17 on 2026-09-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_unit_alter_setting_default_value_alter_setting_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OPERATION', '운전 데이터'), ('MAINTENANCE', '정비 이력')], default='OPERATION', max_length=20, verbose_name='종류')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('stored_path', models.CharField(blank=True, max_length=500, verbose_name='저장 경로')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='파일 크기')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='체크섬(sha256)')),
                ('status', models.CharField(choices=[('PENDING', '검증 대기'), ('VALIDATED', '검증 완료'), ('LOADED', '적재 완료'), ('FAILED', '실패'), ('CANCELED', '취소됨')], default='PENDING', max_length=20, verbose_name='상태')),
                ('row_total', models.IntegerField(default=0, verbose_name='총 행수')),
                ('row_loaded', models.IntegerField(default=0, verbose_name='적재 행수')),
                ('row_skipped', models.IntegerField(default=0, verbose_name='제외 행수')),
                ('row_duplicated', models.IntegerField(default=0, verbose_name='중복 행수')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='데이터 시작')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='데이터 종료')),
                ('validation_report', models.JSONField(blank=True, default=dict, verbose_name='검증 리포트')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('column_mapping_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.columnmappingversion', verbose_name='매핑 버전')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='units.unit', verbose_name='호기')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '업로드 배치',
                'verbose_name_plural': '업로드 배치',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='측정 시각')),
                ('gt_power_mw', models.FloatField(blank=True, null=True)),
                ('ambient_temp_c', models.FloatField(blank=True, null=True)),
                ('gt_exhaust_temp_c', models.FloatField(blank=True, null=True)),
                ('exhaust_flow', models.FloatField(blank=True, null=True)),
                ('fuel_flow', models.FloatField(blank=True, null=True)),
                ('igv_position_pct', models.FloatField(blank=True, null=True)),
                ('hrsg_gas_dp_kpa', models.FloatField(blank=True, null=True)),
                ('gt_backpressure_kpa', models.FloatField(blank=True, null=True)),
                ('stack_temp_c', models.FloatField(blank=True, null=True)),
                ('duct_burner_on', models.BooleanField(blank=True, null=True)),
                ('st_power_mw', models.FloatField(blank=True, null=True)),
                ('steam_flow_tph', models.FloatField(blank=True, null=True)),
                ('feedwater_temp_c', models.FloatField(blank=True, null=True)),
                ('ambient_pressure_kpa', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='units.unit', verbose_name='호기')),
                ('upload_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='ingestion.uploadbatch', verbose_name='업로드 배치')),
            ],
            options={
                'verbose_name': '측정값',
                'verbose_name_plural': '측정값',
            },
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['unit', '-uploaded_at'], name='ingestion_u_unit_id_1f97a1_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['status'], name='ingestion_u_status_5538b5_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['unit', 'timestamp'], name='ingestion_m_unit_id_1f85f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('unit', 'timestamp'), name='uniq_unit_timestamp'),
        ),
    ]
