# Generated by Django 5.2.17 on 2026-09-20 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='키')),
                ('value', models.CharField(max_length=500, verbose_name='현재값')),
                ('value_type', models.CharField(choices=[('INT', '정수'), ('FLOAT', '실수'), ('BOOL', '참/거짓'), ('STRING', '문자열'), ('JSON', 'JSON')], max_length=10, verbose_name='값 타입')),
                ('category', models.CharField(choices=[('FOULING', '오염도'), ('PREPROCESS', '전처리'), ('CLUSTER', '군집화'), ('MODEL', '모델'), ('BENEFIT', '편익'), ('SYSTEM', '시스템')], max_length=20, verbose_name='분류')),
                ('label', models.CharField(max_length=100, verbose_name='표시 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('default_value', models.CharField(max_length=500, verbose_name='기본값')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='최솟값')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='최댓값')),
                ('unit_label', models.CharField(blank=True, max_length=20, verbose_name='단위')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경 일시')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '설정값',
                'verbose_name_plural': '설정값',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='units_setti_categor_defe7a_idx')],
            },
        ),
    ]
