# Generated by Django 5.2.17 on 2026-09-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='호기 코드')),
                ('name', models.CharField(max_length=100, verbose_name='호기명')),
                ('plant_name', models.CharField(blank=True, max_length=100, verbose_name='발전소명')),
                ('gt_model', models.CharField(blank=True, max_length=100, verbose_name='GT 기종')),
                ('rated_power_mw', models.FloatField(verbose_name='GT 정격 출력(MW)')),
                ('rated_st_power_mw', models.FloatField(blank=True, null=True, verbose_name='ST 정격 출력(MW)')),
                ('min_load_mw', models.FloatField(verbose_name='최소 안정 부하(MW)')),
                ('sampling_interval_min', models.PositiveIntegerField(default=10, verbose_name='데이터 주기(분)')),
                ('dp_source', models.CharField(choices=[('DP', '가스측 차압 계측'), ('BACKPRESSURE', 'GT 배압 대체')], default='DP', max_length=20, verbose_name='차압 기준')),
                ('flow_source', models.CharField(choices=[('EXHAUST_FLOW', '배기유량'), ('FUEL_FLOW', '연료유량'), ('IGV', 'IGV 개도')], default='EXHAUST_FLOW', max_length=20, verbose_name='유량 기준')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '호기',
                'verbose_name_plural': '호기',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='setting',
            name='default_value',
            field=models.TextField(verbose_name='기본값'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(verbose_name='현재값'),
        ),
        migrations.CreateModel(
            name='ColumnMappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='버전')),
                ('snapshot', models.JSONField(verbose_name='매핑 스냅샷')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_versions', to='units.unit', verbose_name='호기')),
            ],
            options={
                'verbose_name': '컬럼 매핑 버전',
                'verbose_name_plural': '컬럼 매핑 버전',
                'ordering': ['-version'],
                'unique_together': {('unit', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_field', models.CharField(choices=[('timestamp', 'timestamp'), ('gt_power_mw', 'gt_power_mw'), ('ambient_temp_c', 'ambient_temp_c'), ('gt_exhaust_temp_c', 'gt_exhaust_temp_c'), ('exhaust_flow', 'exhaust_flow'), ('hrsg_gas_dp_kpa', 'hrsg_gas_dp_kpa'), ('stack_temp_c', 'stack_temp_c'), ('duct_burner_on', 'duct_burner_on'), ('fuel_flow', 'fuel_flow'), ('igv_position_pct', 'igv_position_pct'), ('gt_backpressure_kpa', 'gt_backpressure_kpa'), ('st_power_mw', 'st_power_mw'), ('steam_flow_tph', 'steam_flow_tph'), ('feedwater_temp_c', 'feedwater_temp_c'), ('ambient_pressure_kpa', 'ambient_pressure_kpa'), ('humidity_pct', 'humidity_pct')], max_length=40, verbose_name='표준 항목')),
                ('source_column', models.CharField(max_length=200, verbose_name='원본 컬럼명')),
                ('unit_label', models.CharField(blank=True, max_length=30, verbose_name='원본 단위')),
                ('scale_factor', models.FloatField(default=1.0, verbose_name='환산 계수')),
                ('offset', models.FloatField(default=0.0, verbose_name='환산 오프셋')),
                ('bool_rule', models.CharField(blank=True, choices=[('BOOL', '참/거짓 문자열'), ('THRESHOLD', '임계값 초과 시 ON')], max_length=20, verbose_name='해석 규칙')),
                ('bool_threshold', models.FloatField(blank=True, null=True, verbose_name='ON 판정 임계값')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='units.unit', verbose_name='호기')),
            ],
            options={
                'verbose_name': '컬럼 매핑',
                'verbose_name_plural': '컬럼 매핑',
                'ordering': ['unit', 'standard_field'],
                'unique_together': {('unit', 'standard_field')},
            },
        ),
        migrations.CreateModel(
            name='UnitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, verbose_name='키')),
                ('value', models.TextField(verbose_name='값')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경 일시')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_settings', to='units.unit', verbose_name='호기')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '호기별 설정',
                'verbose_name_plural': '호기별 설정',
                'ordering': ['unit', 'key'],
                'unique_together': {('unit', 'key')},
            },
        ),
    ]
