# Generated by Django 5.2.17 on 2026-09-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_snapshot', models.JSONField(default=dict, verbose_name='적용 파라미터')),
                ('delta_dp_kpa', models.FloatField(blank=True, null=True, verbose_name='Δ차압')),
                ('delta_stack_c', models.FloatField(blank=True, null=True, verbose_name='Δ스택온도')),
                ('power_loss_gt_mw', models.FloatField(blank=True, null=True, verbose_name='GT 출력 손실')),
                ('power_loss_st_mw', models.FloatField(blank=True, null=True, verbose_name='ST 출력 손실')),
                ('power_loss_total_mw', models.FloatField(blank=True, null=True, verbose_name='총 출력 손실')),
                ('daily_loss_cost', models.FloatField(blank=True, null=True, verbose_name='일일 손실 비용')),
                ('daily_fuel_loss', models.FloatField(blank=True, null=True, verbose_name='일일 연료 손실')),
                ('cleaning_cost', models.FloatField(blank=True, null=True, verbose_name='세정 비용')),
                ('outage_loss', models.FloatField(blank=True, null=True, verbose_name='정지 손실')),
                ('total_cleaning_cost', models.FloatField(blank=True, null=True, verbose_name='총 세정 비용')),
                ('gross_benefit', models.FloatField(blank=True, null=True, verbose_name='총 회수액(정밀)')),
                ('gross_benefit_simple', models.FloatField(blank=True, null=True, verbose_name='총 회수액(간이)')),
                ('net_benefit', models.FloatField(blank=True, null=True, verbose_name='순편익')),
                ('payback_days', models.FloatField(blank=True, null=True, verbose_name='회수기간')),
                ('roi_pct', models.FloatField(blank=True, null=True, verbose_name='ROI')),
                ('recommended_offset_days', models.IntegerField(blank=True, null=True, verbose_name='권고 세정 시점(일)')),
                ('recommended_cleaning_date', models.DateField(blank=True, null=True, verbose_name='권고 세정 일자')),
                ('recommended_net_benefit', models.FloatField(blank=True, null=True, verbose_name='권고 시점 순편익')),
                ('scenarios', models.JSONField(default=list, verbose_name='시나리오 비교')),
                ('sensitivity', models.JSONField(default=list, verbose_name='민감도')),
                ('warnings', models.JSONField(default=list, verbose_name='경고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': '편익 결과',
                'verbose_name_plural': '편익 결과',
            },
        ),
        migrations.CreateModel(
            name='TrendForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(blank=True, choices=[('LINEAR', '선형'), ('ROBUST', '로버스트 선형'), ('EXPONENTIAL', '포화형')], max_length=20, verbose_name='추세 모델')),
                ('fit_start', models.DateField(blank=True, null=True, verbose_name='적합 시작')),
                ('fit_end', models.DateField(blank=True, null=True, verbose_name='적합 종료')),
                ('coefficients', models.JSONField(default=dict, verbose_name='계수')),
                ('slope_per_day', models.FloatField(blank=True, null=True, verbose_name='진행률(FI/일)')),
                ('r2', models.FloatField(blank=True, null=True, verbose_name='R²')),
                ('mae', models.FloatField(blank=True, null=True, verbose_name='MAE')),
                ('p_value', models.FloatField(blank=True, null=True, verbose_name='p 값')),
                ('threshold_used', models.FloatField(blank=True, null=True, verbose_name='적용 임계치')),
                ('current_fi', models.FloatField(blank=True, null=True, verbose_name='현재 FI')),
                ('eta_date', models.DateField(blank=True, null=True, verbose_name='도달 예상일')),
                ('eta_days', models.IntegerField(blank=True, null=True, verbose_name='D-day')),
                ('eta_lower_date', models.DateField(blank=True, null=True, verbose_name='도달 하한')),
                ('eta_upper_date', models.DateField(blank=True, null=True, verbose_name='도달 상한')),
                ('caution_eta_date', models.DateField(blank=True, null=True, verbose_name='주의 전환 예상일')),
                ('warning_eta_date', models.DateField(blank=True, null=True, verbose_name='경고 전환 예상일')),
                ('exceeded_days', models.IntegerField(blank=True, null=True, verbose_name='초과 일수')),
                ('weekly_increase', models.FloatField(blank=True, null=True, verbose_name='주간 증가량')),
                ('days_since_cleaning', models.IntegerField(blank=True, null=True, verbose_name='세정 후 경과일')),
                ('uncertain', models.BooleanField(default=False, verbose_name='불확실성 높음')),
                ('status', models.CharField(choices=[('OK', '정상'), ('ALREADY_EXCEEDED', '이미 도달'), ('NO_TREND', '추세 미확인'), ('BEYOND_HORIZON', '예측 지평 밖'), ('INSUFFICIENT_DATA', '데이터 부족')], max_length=30, verbose_name='상태')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='안내')),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trend', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': '추세 예측',
                'verbose_name_plural': '추세 예측',
            },
        ),
    ]
