# Generated by Django 5.2.17 on 2026-09-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_benefitresult_trendforecast'),
        ('maintenance', '0001_initial'),
        ('units', '0002_unit_alter_setting_default_value_alter_setting_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window_days', models.PositiveIntegerField(default=30, verbose_name='비교 윈도(일)')),
                ('before_offset_days', models.IntegerField(default=0, verbose_name='세정 전 오프셋')),
                ('after_offset_days', models.IntegerField(default=1, verbose_name='세정 후 오프셋')),
                ('before_start', models.DateTimeField(blank=True, null=True)),
                ('before_end', models.DateTimeField(blank=True, null=True)),
                ('after_start', models.DateTimeField(blank=True, null=True)),
                ('after_end', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict, verbose_name='종합 지표')),
                ('cluster_metrics', models.JSONField(default=list, verbose_name='군집별 지표')),
                ('p_values', models.JSONField(default=dict, verbose_name='유의성')),
                ('common_clusters', models.JSONField(default=list, verbose_name='공통 군집')),
                ('recovery_ratio', models.FloatField(blank=True, null=True, verbose_name='회복률')),
                ('warnings', models.JSONField(default=list, verbose_name='경고')),
                ('cleaning_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='maintenance.cleaningevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model_version_dp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons_as_dp', to='analysis.modelversion')),
                ('model_version_st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons_as_st', to='analysis.modelversion')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='units.unit')),
            ],
            options={
                'verbose_name': '세정 전후 비교',
                'verbose_name_plural': '세정 전후 비교',
                'ordering': ['-created_at'],
            },
        ),
    ]
