# Generated by Django 5.2.17 on 2026-09-20 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_comparisonreport'),
        ('units', '0002_unit_alter_setting_default_value_alter_setting_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRecalcConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='사용')),
                ('trigger', models.CharField(choices=[('ON_UPLOAD', '업로드 완료 시'), ('SCHEDULE', '정해진 일정')], default='ON_UPLOAD', max_length=20, verbose_name='트리거')),
                ('schedule_cron', models.CharField(blank=True, max_length=100, verbose_name='스케줄(cron)')),
                ('period_mode', models.CharField(choices=[('ROLLING', '최근 N개월 고정 창'), ('EXTEND', '기준 분석 시작일 ~ 최신')], default='ROLLING', max_length=20, verbose_name='기간 산정')),
                ('rolling_months', models.PositiveIntegerField(default=12, verbose_name='최근 개월')),
                ('retrain_model', models.BooleanField(default=False, verbose_name='모델 자동 재학습')),
                ('notify_on_grade_change', models.BooleanField(default=True, verbose_name='등급 변화 알림')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_recalc_configs', to='analysis.analysisrun', verbose_name='기준 분석')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_recalc', to='units.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자동 재계산 설정',
                'verbose_name_plural': '자동 재계산 설정',
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lookahead_days', models.PositiveIntegerField(default=60, verbose_name='컷오프 선행 일수')),
                ('cases', models.JSONField(default=list, verbose_name='세정별 결과')),
                ('summary', models.JSONField(default=dict, verbose_name='집계')),
                ('coefficient_suggestion', models.JSONField(default=dict, verbose_name='계수 보정 제안')),
                ('warnings', models.JSONField(default=list, verbose_name='경고')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='units.unit')),
            ],
            options={
                'verbose_name': '백테스트 결과',
                'verbose_name_plural': '백테스트 결과',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', '정보'), ('WARNING', '경고')], default='INFO', max_length=20, verbose_name='수준')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(blank=True, verbose_name='내용')),
                ('payload', models.JSONField(default=dict, verbose_name='상세')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analysis.analysisrun')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='units.unit')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analysis_no_created_53800f_idx'), models.Index(fields=['is_read'], name='analysis_no_is_read_190f89_idx')],
            },
        ),
    ]
