# Generated by Django 5.2.17 on 2026-09-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_autorecalcconfig_backtestresult_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="baseline_periods",
            field=models.JSONField(blank=True, default=list, verbose_name="학습 구간 목록"),
        ),
    ]
