"""체크리스트 항목 시드 `[임시값]` (specs/07 §2.1).

사내 데이터 요청 양식(스프레드시트)을 아직 받지 못했다. 요구사항에 적힌 분류로 만든 가상 항목이다.
`[실무 논의]` P8 — 양식 원본을 받으면 관리자 모드에서 xlsx 로 가져와 교체한다.

각 행: (분류, 한국어 이름, 영어 이름, 단위, 필수, 이유(한), 이유(영), 계산기 입력, 출처)
"""

FORM, ADDED = "FORM", "ADDED"

SEED_ITEMS: tuple[tuple, ...] = (
    # --- 가스터빈 (양식) ---
    (
        "GT",
        "GT 모델·제조사",
        "GT model and manufacturer",
        "",
        True,
        "운전 한계와 정격을 찾는 기준",
        "Basis for operating limits and ratings",
        True,
        FORM,
    ),
    (
        "GT",
        "GT 출력",
        "GT power output",
        "MW",
        True,
        "부분 부하를 보정해 손실을 계산",
        "Corrects loss for part load",
        True,
        FORM,
    ),
    (
        "GT",
        "대기온도",
        "Ambient temperature",
        "℃",
        True,
        "운전 조건을 같은 기준으로 비교",
        "Compares operation on the same basis",
        False,
        FORM,
    ),
    (
        "GT",
        "대기압",
        "Ambient pressure",
        "kPa",
        False,
        "출력 보정",
        "Output correction",
        False,
        FORM,
    ),
    (
        "GT",
        "상대습도",
        "Relative humidity",
        "%",
        False,
        "출력 보정",
        "Output correction",
        False,
        FORM,
    ),
    (
        "GT",
        "IGV 개도",
        "IGV opening",
        "%",
        False,
        "배기 유량 추정",
        "Estimates exhaust flow",
        False,
        FORM,
    ),
    (
        "GT",
        "누적 운전시간·기동 횟수",
        "Operating hours and number of starts",
        "h, 회",
        False,
        "오염 진행 정도 판단",
        "Indicates fouling progression",
        False,
        FORM,
    ),
    # --- 연료 ---
    (
        "FUEL",
        "연료 종류",
        "Fuel type",
        "",
        True,
        "배기가스 성분·오염 특성 판단",
        "Determines flue gas composition and fouling tendency",
        False,
        FORM,
    ),
    (
        "FUEL",
        "연료 유량",
        "Fuel flow",
        "Nm³/h",
        True,
        "열소비율 계산",
        "Heat rate calculation",
        False,
        FORM,
    ),
    (
        "FUEL",
        "저위발열량",
        "Lower heating value",
        "kJ/Nm³",
        False,
        "열소비율 계산",
        "Heat rate calculation",
        False,
        FORM,
    ),
    (
        "FUEL",
        "연료 조성",
        "Fuel composition",
        "",
        False,
        "황·회분에 의한 오염 가능성 판단",
        "Assesses fouling from sulfur and ash",
        False,
        FORM,
    ),
    # --- 배기가스 ---
    (
        "EXHAUST",
        "GT 배기온도",
        "GT exhaust temperature",
        "℃",
        True,
        "HRSG 입구 열량과 운전 상태 판정",
        "HRSG inlet heat and operating state",
        True,
        FORM,
    ),
    (
        "EXHAUST",
        "배기가스 유량",
        "Exhaust gas flow",
        "kg/s",
        True,
        "열 회수량 계산",
        "Heat recovery calculation",
        False,
        FORM,
    ),
    (
        "EXHAUST",
        "GT 배압",
        "GT exhaust back pressure",
        "kPa",
        True,
        "오염에 따른 배압 상승과 GT 출력 손실",
        "Back pressure rise from fouling and GT output loss",
        True,
        FORM,
    ),
    (
        "EXHAUST",
        "HRSG 가스측 차압",
        "HRSG gas-side differential pressure",
        "kPa",
        True,
        "전열면 오염 정도",
        "Indicates tube bank fouling",
        False,
        FORM,
    ),
    (
        "EXHAUST",
        "굴뚝 온도",
        "Stack temperature",
        "℃",
        True,
        "열 회수 저하와 ST 출력 손실",
        "Reduced heat recovery and ST output loss",
        True,
        FORM,
    ),
    (
        "EXHAUST",
        "덕트버너 사용 여부·연료량",
        "Duct burner operation and fuel",
        "",
        False,
        "추가 열량 보정",
        "Corrects for supplementary firing",
        False,
        FORM,
    ),
    # --- 급수 ---
    (
        "FEEDWATER",
        "급수 유량",
        "Feedwater flow",
        "t/h",
        True,
        "열수지 계산",
        "Heat balance",
        False,
        FORM,
    ),
    (
        "FEEDWATER",
        "급수 온도",
        "Feedwater temperature",
        "℃",
        True,
        "절탄기 열 흡수량 계산",
        "Economizer heat duty",
        False,
        FORM,
    ),
    (
        "FEEDWATER",
        "급수 압력",
        "Feedwater pressure",
        "bar",
        False,
        "물성 계산",
        "Property calculation",
        False,
        FORM,
    ),
    (
        "FEEDWATER",
        "절탄기 입구 온도",
        "Economizer inlet temperature",
        "℃",
        False,
        "절탄기 성능 판단",
        "Economizer performance",
        False,
        FORM,
    ),
    # --- 증기 ---
    (
        "STEAM",
        "압력단별 증기 유량·압력·온도",
        "Steam flow, pressure and temperature per pressure level",
        "t/h, bar, ℃",
        True,
        "증기 생산량과 열 회수 판단",
        "Steam production and heat recovery",
        False,
        FORM,
    ),
    (
        "STEAM",
        "ST 출력",
        "ST power output",
        "MW",
        True,
        "ST 출력 손실 산정",
        "ST output loss",
        False,
        FORM,
    ),
    # --- 배출가스 ---
    (
        "EMISSION",
        "NOx",
        "NOx",
        "ppm",
        False,
        "SCR 상태와 암모니아염 오염 판단",
        "SCR condition and ammonium salt fouling",
        False,
        FORM,
    ),
    ("EMISSION", "CO", "CO", "ppm", False, "연소 상태 확인", "Combustion condition", False, FORM),
    (
        "EMISSION",
        "O₂",
        "O₂",
        "%",
        False,
        "배기가스 유량 보정",
        "Exhaust flow correction",
        False,
        FORM,
    ),
    (
        "EMISSION",
        "암모니아 주입량",
        "Ammonia injection rate",
        "kg/h",
        False,
        "암모니아염 생성 가능성",
        "Ammonium salt formation risk",
        False,
        FORM,
    ),
    # --- 열교환 모듈 사양 ---
    (
        "MODULE",
        "모듈 배치도",
        "Module arrangement drawing",
        "",
        True,
        "세정 위치·작업 범위 결정",
        "Defines cleaning locations and scope",
        False,
        FORM,
    ),
    (
        "MODULE",
        "튜브 재질·외경·두께",
        "Tube material, OD and thickness",
        "",
        True,
        "세정 공법 선택",
        "Selects the cleaning method",
        False,
        FORM,
    ),
    (
        "MODULE",
        "핀 형태·높이·피치·두께",
        "Fin type, height, pitch and thickness",
        "",
        True,
        "오염 부착 특성·세정 효과 판단",
        "Fouling deposition and cleaning effect",
        False,
        FORM,
    ),
    (
        "MODULE",
        "모듈별 전열면적·열 수",
        "Heat transfer area and rows per module",
        "m²",
        False,
        "작업량·소요 일수 산정",
        "Estimates workload and duration",
        False,
        FORM,
    ),
    # --- 설계값 ---
    (
        "DESIGN",
        "설계 열정산(Heat Balance)",
        "Design heat balance",
        "",
        True,
        "청정 상태 기준값",
        "Clean-condition reference",
        False,
        FORM,
    ),
    (
        "DESIGN",
        "설계 배압",
        "Design back pressure",
        "kPa",
        True,
        "청정 배압 기준",
        "Clean back pressure reference",
        True,
        FORM,
    ),
    (
        "DESIGN",
        "설계 굴뚝 온도",
        "Design stack temperature",
        "℃",
        True,
        "청정 굴뚝 온도 기준",
        "Clean stack temperature reference",
        True,
        FORM,
    ),
    (
        "DESIGN",
        "설계 핀치·어프로치",
        "Design pinch and approach",
        "℃",
        False,
        "핀치·어프로치 판정 기준",
        "Reference for pinch and approach checks",
        True,
        FORM,
    ),
    # --- 핀치·어프로치 (추가) ---
    (
        "PINCH",
        "압력단별 드럼 압력",
        "Drum pressure per pressure level",
        "bar(g)",
        True,
        "포화온도 계산",
        "Saturation temperature",
        True,
        ADDED,
    ),
    (
        "PINCH",
        "절탄기 출구 급수 온도",
        "Economizer outlet water temperature",
        "℃",
        True,
        "어프로치 계산(스티밍 여유)",
        "Approach (steaming margin)",
        True,
        ADDED,
    ),
    (
        "PINCH",
        "증발기 출구 가스 온도",
        "Evaporator outlet gas temperature",
        "℃",
        True,
        "핀치 계산(열 회수 상태)",
        "Pinch (heat recovery condition)",
        True,
        ADDED,
    ),
    # --- 일정·현장 조건 (추가) ---
    (
        "SCHEDULE",
        "희망 세정 시기·가용 정지 기간",
        "Preferred cleaning date and available outage",
        "",
        True,
        "공법·인력 계획",
        "Plans method and crew",
        False,
        ADDED,
    ),
    (
        "SCHEDULE",
        "현장 접근 경로·작업 공간",
        "Site access and working space",
        "",
        True,
        "장비 반입 가능 여부",
        "Equipment access",
        False,
        ADDED,
    ),
    (
        "SCHEDULE",
        "점검구 위치",
        "Access door locations",
        "",
        True,
        "세정 위치 접근",
        "Access to cleaning locations",
        False,
        ADDED,
    ),
    (
        "SCHEDULE",
        "유틸리티(전원·압축공기·용수)",
        "Utilities (power, compressed air, water)",
        "",
        True,
        "장비 운용 준비",
        "Equipment operation",
        False,
        ADDED,
    ),
    (
        "SCHEDULE",
        "출입·안전 절차",
        "Site access and safety procedures",
        "",
        True,
        "작업 허가 준비",
        "Work permit preparation",
        False,
        ADDED,
    ),
    # --- 데이터 범위 (추가) ---
    (
        "DATA_SCOPE",
        "운전 데이터 기간(세정 전후)",
        "Operating data period (before and after cleaning)",
        "",
        True,
        "세정 효과 비교",
        "Compares before and after cleaning",
        False,
        ADDED,
    ),
    (
        "DATA_SCOPE",
        "기록 주기",
        "Logging interval",
        "분",
        False,
        "데이터 처리 방법 결정",
        "Determines data processing",
        False,
        ADDED,
    ),
    (
        "DATA_SCOPE",
        "파일 형식",
        "File format",
        "",
        False,
        "데이터 변환 준비",
        "Prepares data conversion",
        False,
        ADDED,
    ),
)
