# Generated by Django 5.2.17 on 2026-09-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_unit_alter_setting_default_value_alter_setting_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_at', models.DateTimeField(verbose_name='세정 일자')),
                ('cleaned_end_at', models.DateTimeField(blank=True, null=True, verbose_name='세정 종료 일자')),
                ('method', models.CharField(choices=[('WATER_WASH', '수세'), ('CHEMICAL', '화학세정'), ('DRY_ICE', '드라이아이스'), ('MECHANICAL', '기계적 청소'), ('SOOT_BLOWING', '수트 블로잉'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='세정 방법')),
                ('method_detail', models.CharField(blank=True, max_length=200, verbose_name='세정 방법 상세')),
                ('cost', models.BigIntegerField(blank=True, null=True, verbose_name='비용(원)')),
                ('outage_days', models.FloatField(blank=True, null=True, verbose_name='정지 일수')),
                ('source', models.CharField(choices=[('MANUAL', '수동 등록'), ('EXTRACTED', '정비 이력 추출')], default='MANUAL', max_length=20, verbose_name='등록 경로')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_events', to='units.unit', verbose_name='호기')),
            ],
            options={
                'verbose_name': '세정 이력',
                'verbose_name_plural': '세정 이력',
                'ordering': ['-cleaned_at'],
                'indexes': [models.Index(fields=['unit', 'cleaned_at'], name='maintenance_unit_id_df3e3e_idx')],
            },
        ),
    ]
