# Generated by Django 5.2.17 on 2026-09-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('units', '0002_unit_alter_setting_default_value_alter_setting_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='작업일')),
                ('work_type', models.CharField(blank=True, max_length=50, verbose_name='작업구분')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='내용')),
                ('cost', models.BigIntegerField(blank=True, null=True, verbose_name='비용')),
                ('duration_days', models.FloatField(blank=True, null=True, verbose_name='소요일수')),
                ('worker', models.CharField(blank=True, max_length=100, verbose_name='작업자')),
                ('is_fouling_related', models.BooleanField(default=False, verbose_name='오염 관련')),
                ('matched_keywords', models.JSONField(default=list, verbose_name='매칭 키워드')),
                ('match_score', models.FloatField(default=0.0, verbose_name='매칭 점수')),
                ('match_category', models.CharField(blank=True, max_length=20, verbose_name='매칭 분류')),
                ('review_status', models.CharField(choices=[('PENDING', '검토 대기'), ('ACCEPTED', '승인됨'), ('IGNORED', '무시됨')], default='PENDING', max_length=20, verbose_name='검토 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaning_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_records', to='maintenance.cleaningevent')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='units.unit', verbose_name='호기')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='ingestion.uploadbatch')),
            ],
            options={
                'verbose_name': '정비 이력',
                'verbose_name_plural': '정비 이력',
                'ordering': ['-work_date'],
            },
        ),
        migrations.AddField(
            model_name='cleaningevent',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maintenance.maintenancerecord', verbose_name='추출 출처'),
        ),
        migrations.CreateModel(
            name='FoulingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='키워드')),
                ('category', models.CharField(choices=[('CLEANING', '세정'), ('FOULING', '오염 징후'), ('INSPECTION', '점검'), ('EXCLUDE', '제외어')], max_length=20, verbose_name='분류')),
                ('weight', models.FloatField(default=1.0, verbose_name='가중치')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '오염 키워드',
                'verbose_name_plural': '오염 키워드',
                'ordering': ['category', 'keyword'],
                'unique_together': {('keyword', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['unit', '-work_date'], name='maintenance_unit_id_8c65c8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['is_fouling_related'], name='maintenance_is_foul_9a3c69_idx'),
        ),
    ]
