# Generated by Django 5.2.17 on 2026-10-10 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="버전")),
                ("is_placeholder", models.BooleanField(default=True, verbose_name="임시값")),
                ("is_active", models.BooleanField(default=True, verbose_name="사용")),
                ("note", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="공법")),
                ("cleaning_cost_won", models.FloatField(verbose_name="세정 비용(원)")),
                ("outage_days", models.FloatField(verbose_name="정지 일수(일)")),
                ("recovery_ratio", models.FloatField(verbose_name="회복률")),
            ],
            options={
                "verbose_name": "세정 공법",
                "verbose_name_plural": "세정 공법",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("recovery_ratio__gt", 0), ("recovery_ratio__lte", 1)),
                        name="cleaningmethod_recovery_ratio_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cleaning_cost_won__gte", 0)),
                        name="cleaningmethod_cost_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outage_days__gte", 0)),
                        name="cleaningmethod_outage_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GtModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="버전")),
                ("is_placeholder", models.BooleanField(default=True, verbose_name="임시값")),
                ("is_active", models.BooleanField(default=True, verbose_name="사용")),
                ("note", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="모델 이름")),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, verbose_name="제조사"),
                ),
                ("rated_gt_mw", models.FloatField(verbose_name="GT 정격 출력(MW)")),
                (
                    "rated_st_mw",
                    models.FloatField(blank=True, null=True, verbose_name="ST 정격 출력(MW)"),
                ),
                ("design_backpressure_kpa", models.FloatField(verbose_name="설계 배압(kPa)")),
                ("backpressure_alarm_kpa", models.FloatField(verbose_name="배압 경보(kPa)")),
                ("backpressure_trip_kpa", models.FloatField(verbose_name="배압 트립(kPa)")),
                ("design_exhaust_temp_c", models.FloatField(verbose_name="설계 배기온도(℃)")),
                ("exhaust_temp_alarm_c", models.FloatField(verbose_name="배기온도 경보(℃)")),
                ("exhaust_temp_trip_c", models.FloatField(verbose_name="배기온도 트립(℃)")),
                ("design_stack_temp_c", models.FloatField(verbose_name="설계 굴뚝 온도(℃)")),
            ],
            options={
                "verbose_name": "GT 운전 한계",
                "verbose_name_plural": "GT 운전 한계",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("backpressure_alarm_kpa__lt", models.F("backpressure_trip_kpa"))
                        ),
                        name="gtmodel_backpressure_alarm_lt_trip",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("exhaust_temp_alarm_c__lt", models.F("exhaust_temp_trip_c"))
                        ),
                        name="gtmodel_exhaust_alarm_lt_trip",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rated_gt_mw__gt", 0)), name="gtmodel_rated_gt_positive"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalcParameterSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version_label",
                    models.CharField(max_length=20, unique=True, verbose_name="버전"),
                ),
                ("params", models.JSONField(verbose_name="파라미터")),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                ("is_seed", models.BooleanField(default=False, verbose_name="시드값 그대로")),
                ("note", models.TextField(blank=True, verbose_name="변경 사유")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "계산 파라미터 세트",
                "verbose_name_plural": "계산 파라미터 세트",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="calcparameterset_single_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SmpPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_won_per_kwh", models.FloatField(verbose_name="SMP(원/kWh)")),
                ("as_of_date", models.DateField(verbose_name="기준일")),
                (
                    "period_label",
                    models.CharField(blank=True, max_length=50, verbose_name="기간 표기"),
                ),
                ("source", models.CharField(max_length=200, verbose_name="출처")),
                ("is_estimate", models.BooleanField(default=False, verbose_name="추정값")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="등록 일시")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMP",
                "verbose_name_plural": "SMP",
                "ordering": ["-as_of_date", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("value_won_per_kwh__gt", 0)), name="smp_positive"
                    )
                ],
            },
        ),
    ]
