# Generated by Django 5.2.17 on 2026-09-20 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('DELETE', '삭제'), ('ACTIVATE', '활성화'), ('RESTORE', '복원'), ('ROLLBACK', '롤백'), ('TRAIN', '학습')], max_length=20, verbose_name='동작')),
                ('target_type', models.CharField(max_length=50, verbose_name='대상 종류')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='대상 식별자')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='대상 표시명')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='변경 전')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='변경 후')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='행위자')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='common_audi_created_fa4caf_idx'), models.Index(fields=['target_type', '-created_at'], name='common_audi_target__d6fa3a_idx'), models.Index(fields=['actor', '-created_at'], name='common_audi_actor_i_bd962b_idx')],
            },
        ),
    ]
