# Generated by Django 5.2.17 on 2026-10-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "생성"),
                            ("UPDATE", "수정"),
                            ("DELETE", "삭제"),
                            ("ACTIVATE", "활성화"),
                            ("RESTORE", "복원"),
                            ("APPROVE", "승인"),
                            ("REJECT", "반려"),
                        ],
                        max_length=20,
                        verbose_name="동작",
                    ),
                ),
                ("target_type", models.CharField(max_length=50, verbose_name="대상 종류")),
                (
                    "target_id",
                    models.CharField(blank=True, max_length=50, verbose_name="대상 식별자"),
                ),
                (
                    "target_label",
                    models.CharField(blank=True, max_length=200, verbose_name="대상 표시명"),
                ),
                ("before", models.JSONField(blank=True, null=True, verbose_name="변경 전")),
                ("after", models.JSONField(blank=True, null=True, verbose_name="변경 후")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="일시")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="행위자",
                    ),
                ),
            ],
            options={
                "verbose_name": "감사 로그",
                "verbose_name_plural": "감사 로그",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="common_audi_created_fa4caf_idx"),
                    models.Index(
                        fields=["target_type", "-created_at"], name="common_audi_target__d6fa3a_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="common_audi_actor_i_bd962b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True, verbose_name="키")),
                ("value", models.TextField(verbose_name="현재값")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INT", "정수"),
                            ("FLOAT", "실수"),
                            ("BOOL", "참/거짓"),
                            ("STRING", "문자열"),
                            ("TEXT", "긴 문자열"),
                            ("JSON", "JSON"),
                        ],
                        max_length=10,
                        verbose_name="값 타입",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTH", "인증"),
                            ("CHAT", "질의응답"),
                            ("RAG", "검색(RAG)"),
                            ("CHUNK", "청크"),
                            ("DOCUMENT", "문서"),
                            ("LLM", "LLM"),
                            ("CALC", "계산기"),
                            ("CHECKLIST", "체크리스트"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="표시 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("default_value", models.TextField(verbose_name="기본값")),
                ("min_value", models.FloatField(blank=True, null=True, verbose_name="최솟값")),
                ("max_value", models.FloatField(blank=True, null=True, verbose_name="최댓값")),
                ("unit_label", models.CharField(blank=True, max_length=20, verbose_name="단위")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="변경 일시")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경자",
                    ),
                ),
            ],
            options={
                "verbose_name": "설정값",
                "verbose_name_plural": "설정값",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(fields=["category"], name="common_sett_categor_e0486d_idx")
                ],
            },
        ),
    ]
