# Generated by Django 5.2.17 on 2026-10-10 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GT", "가스터빈"),
                            ("FUEL", "연료"),
                            ("EXHAUST", "배기가스"),
                            ("FEEDWATER", "급수"),
                            ("STEAM", "증기"),
                            ("EMISSION", "배출가스"),
                            ("MODULE", "열교환 모듈 사양"),
                            ("DESIGN", "설계값"),
                            ("PINCH", "핀치·어프로치"),
                            ("SCHEDULE", "일정·현장 조건"),
                            ("DATA_SCOPE", "데이터 범위"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                ("name_ko", models.CharField(max_length=200, verbose_name="항목명")),
                ("name_en", models.CharField(max_length=200, verbose_name="항목명(영문)")),
                ("unit", models.CharField(blank=True, max_length=40, verbose_name="단위")),
                ("is_required", models.BooleanField(default=True, verbose_name="필수")),
                (
                    "why_needed_ko",
                    models.CharField(blank=True, max_length=300, verbose_name="필요한 이유"),
                ),
                (
                    "why_needed_en",
                    models.CharField(blank=True, max_length=300, verbose_name="필요한 이유(영문)"),
                ),
                (
                    "is_calculator_input",
                    models.BooleanField(default=False, verbose_name="계산기 입력"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "source",
                    models.CharField(
                        choices=[("FORM", "사내 양식"), ("ADDED", "앱에서 추가")],
                        default="FORM",
                        max_length=10,
                        verbose_name="출처",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="사용")),
                ("is_placeholder", models.BooleanField(default=True, verbose_name="임시값")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="버전")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
            ],
            options={
                "verbose_name": "체크리스트 항목 템플릿",
                "verbose_name_plural": "체크리스트 항목 템플릿",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name_ko"), name="checklist_template_unique_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="요청 건 이름")),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="희망 회신일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "진행 중"),
                            ("DONE", "완료"),
                            ("ARCHIVED", "보관"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("template_snapshot_at", models.DateTimeField(verbose_name="템플릿 복사 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 요청 건",
                "verbose_name_plural": "데이터 요청 건",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DataRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GT", "가스터빈"),
                            ("FUEL", "연료"),
                            ("EXHAUST", "배기가스"),
                            ("FEEDWATER", "급수"),
                            ("STEAM", "증기"),
                            ("EMISSION", "배출가스"),
                            ("MODULE", "열교환 모듈 사양"),
                            ("DESIGN", "설계값"),
                            ("PINCH", "핀치·어프로치"),
                            ("SCHEDULE", "일정·현장 조건"),
                            ("DATA_SCOPE", "데이터 범위"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                ("name_ko", models.CharField(max_length=200, verbose_name="항목명")),
                ("name_en", models.CharField(max_length=200, verbose_name="항목명(영문)")),
                ("unit", models.CharField(blank=True, max_length=40, verbose_name="단위")),
                ("is_required", models.BooleanField(default=True, verbose_name="필수")),
                (
                    "why_needed_ko",
                    models.CharField(blank=True, max_length=300, verbose_name="필요한 이유"),
                ),
                (
                    "why_needed_en",
                    models.CharField(blank=True, max_length=300, verbose_name="필요한 이유(영문)"),
                ),
                (
                    "is_calculator_input",
                    models.BooleanField(default=False, verbose_name="계산기 입력"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "미수신"),
                            ("RECEIVED", "받음"),
                            ("NOT_APPLICABLE", "해당 없음"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="받은 일시"),
                ),
                ("memo", models.CharField(blank=True, max_length=500, verbose_name="메모")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checklist.datarequest",
                        verbose_name="요청 건",
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="checklist.checklisttemplateitem",
                        verbose_name="원본 템플릿 항목",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 요청 항목",
                "verbose_name_plural": "데이터 요청 항목",
                "ordering": ["order", "id"],
            },
        ),
    ]
